### ISSUE TITLE
Move this repo to f-actions

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/font-browser-tests-action#1]
@chrissimpkins I'm almost done with this action so I'd like to move it to https://github.com/f-actions. We should also rename it to diffenator2

**Comment by chrissimpkins** [comment]
Sounds great Marc! I will add you to the org so that you can transfer it whenever you are ready.

**Comment by chrissimpkins** [comment]
done

**Comment by m4rc1e** [comment]
Boom done. On home straight now.
